# -*- coding: utf-8 -*-
"""Demo  SidaProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GIA0YjinEAwcJF9QmG8MFBi7TexGubvX
"""

!pip install ezdxf
!pip install reportlab

import ezdxf
import csv
import io
import re
import ast
import math
import pandas as pd
from google.colab import files
import traceback


# -----------------------------------------------------------------------------------------
# DXF → CSV extractor   (output stored in variable instead of file)
# -----------------------------------------------------------------------------------------

def get_entity_color(entity, doc):
    if entity.dxf.hasattr("true_color"):
        return entity.rgb
    if entity.dxf.color not in (0, 256):
        return entity.dxf.color
    if entity.dxf.color == 256:
        layer = doc.layers.get(entity.dxf.layer)
        return layer.dxf.color
    return 7


def extract_entity_data(entity, doc):
    etype = entity.dxftype()
    data = {
        "Type": etype,
        "Layer": entity.dxf.layer if entity.dxf.hasattr("layer") else "",
        "ColorCode": get_entity_color(entity, doc),
        "StartX": "", "StartY": "", "StartZ": "",
        "EndX": "", "EndY": "", "EndZ": "",
        "Details": "",
    }

    try:
        if etype == "LINE":
            sx, sy, sz = entity.dxf.start
            ex, ey, ez = entity.dxf.end
            data.update({
                "StartX": sx, "StartY": sy, "StartZ": sz,
                "EndX": ex, "EndY": ey, "EndZ": ez,
                "Details": f"LINE from {entity.dxf.start} to {entity.dxf.end}",
            })

        elif etype == "CIRCLE":
            cx, cy, cz = entity.dxf.center
            data.update({
                "StartX": cx, "StartY": cy, "StartZ": cz,
                "Details": f"center={entity.dxf.center}, radius={entity.dxf.radius}",
            })

        elif etype == "ARC":
            cx, cy, cz = entity.dxf.center
            data.update({
                "StartX": cx, "StartY": cy, "StartZ": cz,
                "Details": (
                    f"center={entity.dxf.center}, radius={entity.dxf.radius}, "
                    f"start_angle={entity.dxf.start_angle}, end_angle={entity.dxf.end_angle}"
                ),
            })

        elif etype == "LWPOLYLINE":
            pts = [tuple(p[:2]) for p in entity.get_points()]
            if pts:
                data["StartX"], data["StartY"] = pts[0]
            data["Details"] = f"points={pts}"

        elif etype == "POLYLINE":
            pts = [tuple(v.dxf.location) for v in entity.vertices]
            if pts:
                data["StartX"], data["StartY"], data["StartZ"] = pts[0]
            data["Details"] = f"points={pts}"

        elif etype == "TEXT":
            ix, iy, iz = entity.dxf.insert
            data.update({
                "StartX": ix, "StartY": iy, "StartZ": iz,
                "Details": f"text={entity.dxf.text}",
            })

        elif etype == "MTEXT":
            ix, iy, iz = entity.dxf.insert
            data.update({
                "StartX": ix, "StartY": iy, "StartZ": iz,
                "Details": f"text={entity.text}",
            })

        elif etype == "INSERT":
            ix, iy, iz = entity.dxf.insert
            data.update({
                "StartX": ix, "StartY": iy, "StartZ": iz,
                "Details": f"block_name={entity.dxf.name}",
            })

        else:
            data["Details"] = "Unsupported entity type"

    except Exception:
        data["Details"] = "Error parsing entity"

    return data


def dxf_to_csv_in_memory(dxf_path):
    try:
        doc = ezdxf.readfile(dxf_path)
        msp = doc.modelspace()

        rows = [extract_entity_data(e, doc) for e in msp]

        output = io.StringIO()
        writer = csv.DictWriter(output,
            fieldnames=["Type","Layer","ColorCode","StartX","StartY","StartZ",
                        "EndX","EndY","EndZ","Details"])
        writer.writeheader()
        writer.writerows(rows)

        return output.getvalue()

    except Exception as e:
        print("❌ Error:", e)
        print(traceback.format_exc())
        return ""

from google.colab import drive
drive.mount('/content/drive')

import os
# dxf_filename = "/content/drive/MyDrive/SIDA/bion.dxf"
# dxf_filename = "/content/drive/MyDrive/SIDA/Pioneer drg. 20.11.25.dxf"
# dxf_filename = "/content/drive/MyDrive/SIDA/sub4 (10.11.2025).dxf"
# dxf_filename = "/content/drive/MyDrive/SIDA/converted @ Two Block.dxf"
# dxf_filename = "/content/drive/MyDrive/SIDA/03-04-2026/Sub-B.dxf"
# dxf_filename = "/content/drive/MyDrive/SIDA/03-04-2026/sub 6.dxf"
# dxf_filename = "/content/drive/MyDrive/SIDA/Converted ABC.dxf"
# dxf_filename = "/content/drive/MyDrive/SIDA/03-04-2026/sub 3.dxf"
# dxf_filename = "/content/drive/MyDrive/SIDA/COMPOUNDING DRAWING.dxf"
# dxf_filename = "/content/drive/MyDrive/SIDA/ODA_DXF_file/ODA_COMPOUNDING DRAWING.dxf"
dxf_filename = "/content/drive/MyDrive/SIDA/Teigha File Converter/COMPOUNDING DRAWING_teh.dxf"
FileName = os.path.splitext(os.path.basename(dxf_filename))[0]




# Convert to CSV (in variable)
csv_text = dxf_to_csv_in_memory(dxf_filename)

print("\n🔹 CSV extract preview:")
print(csv_text[:400])

# Load CSV text into pandas DataFrame
from io import StringIO
df = pd.read_csv(StringIO(csv_text))

df.head()

from google.colab import files

df.to_csv(f"{FileName}.csv", index=False)
files.download(f"{FileName}.csv")

import re, ast, math

SCALE = 1.0  # 1 mm = 1 m  (adjust if needed)

# ----------------------------------------------------------
# Extract Polyline Points  (removes Z coordinate)
# ----------------------------------------------------------
def extract_points(details):
    if not isinstance(details, str):
        return []
    if "points=" not in details:
        return []

    try:
        match = re.search(r"points\s*=\s*(\[.*\])", details)
        if not match:
            return []

        cleaned = re.sub(r"np\.float64\((.*?)\)", r"\1", match.group(1))
        pts = ast.literal_eval(cleaned)

        # --- IMPORTANT FIX ---
        # Convert (x, y, z) → (x, y)
        pts2 = [(p[0], p[1]) for p in pts]

        return pts2

    except:
        return []


# ----------------------------------------------------------
# Geometry helpers
# ----------------------------------------------------------
def polygon_area(points):
    if len(points) < 3:
        return 0

    pts = points + [points[0]]
    area = sum(
        pts[i][0] * pts[i + 1][1] - pts[i + 1][0] * pts[i][1]
        for i in range(len(points))
    )
    return abs(area) / 2 * SCALE * SCALE


def dist(p1, p2):
    return math.dist(p1, p2) * SCALE


def horizontal_distance(x1, x2):
    return abs(x1 - x2) * SCALE


def vertical_distance(y1, y2):
    return abs(y1 - y2) * SCALE


# ----------------------------------------------------------
# CAD Wrapper
# ----------------------------------------------------------
class CADData:
    def __init__(self, df):
        self.df = df

    def get_entities(self, ColorCode, etype):

        # Force ColorCode column to int (safe conversion)
        df_fixed = self.df.copy()
        df_fixed["ColorCode"] = df_fixed["ColorCode"].astype(str).str.extract(r"(\d+)").astype(int)

        # If etype is LWPOLYLINE, allow both forms
        if etype == "LWPOLYLINE":
            valid_types = ["LWPOLYLINE", "POLYLINE"]
        else:
            valid_types = [etype]

        rows = df_fixed[
            (df_fixed["ColorCode"] == int(ColorCode)) &
            (df_fixed["Type"].isin(valid_types))
        ]

        return rows if not rows.empty else None




    def get_entity(self, ColorCode, etype):
        rows = self.get_entities(ColorCode, etype)
        return rows.iloc[0] if rows is not None else None



# ----------------------------------------------------------
# Area / Length
# ----------------------------------------------------------
def calc_area(entity):
    return polygon_area(extract_points(entity["Details"]))


def calc_length(entity):
    return dist(
        (entity["StartX"], entity["StartY"]),
        (entity["EndX"], entity["EndY"])
    )


# ----------------------------------------------------------
# Point-to-Segment Distance
# ----------------------------------------------------------
def dist_point_to_segment(px, py, x1, y1, x2, y2):
    seg_len_sq = (x2 - x1)**2 + (y2 - y1)**2
    if seg_len_sq == 0:
        return math.dist((px, py), (x1, y1)) * SCALE

    t = max(
        0,
        min(1, ((px - x1)*(x2 - x1) + (py - y1)*(y2 - y1)) / seg_len_sq)
    )

    proj_x = x1 + t * (x2 - x1)
    proj_y = y1 + t * (y2 - y1)

    return math.dist((px, py), (proj_x, proj_y)) * SCALE


# ----------------------------------------------------------
# Extract segment list from LINE or POLYLINE
# ----------------------------------------------------------
def segment_list(entity):
    if entity["Type"].lower() == "line":
        return [(entity["StartX"], entity["StartY"],
                 entity["EndX"], entity["EndY"])]

    pts = extract_points(entity["Details"])
    segs = []
    for i in range(len(pts)-1):
        x1, y1 = pts[i]
        x2, y2 = pts[i+1]
        segs.append((x1, y1, x2, y2))

    return segs


# ----------------------------------------------------------
# Updated Parallel / Closest Distance Calculator
# ----------------------------------------------------------
def calc_parallel_distance(entityA, entityB):

    segA = segment_list(entityA)
    segB = segment_list(entityB)

    min_dist = float("inf")

    for (Ax1, Ay1, Ax2, Ay2) in segA:
        for (Bx1, By1, Bx2, By2) in segB:

            Avertical = abs(Ax2 - Ax1) < 1e-9
            Bvertical = abs(Bx2 - Bx1) < 1e-9
            Ahorizontal = abs(Ay2 - Ay1) < 1e-9
            Bhorizontal = abs(By2 - By1) < 1e-9

            # CASE 1: both vertical → parallel
            if Avertical and Bvertical:
                min_dist = min(min_dist, abs(Ax1 - Bx1) * SCALE)
                continue

            # CASE 2: both horizontal → parallel
            if Ahorizontal and Bhorizontal:
                min_dist = min(min_dist, abs(Ay1 - By1) * SCALE)
                continue

            # DEFAULT: compute perpendicular distances
            d1 = dist_point_to_segment(Ax1, Ay1, Bx1, By1, Bx2, By2)
            d2 = dist_point_to_segment(Ax2, Ay2, Bx1, By1, Bx2, By2)
            d3 = dist_point_to_segment(Bx1, By1, Ax1, Ay1, Ax2, Ay2)
            d4 = dist_point_to_segment(Bx2, By2, Ax1, Ay1, Ax2, Ay2)

            min_dist = min(min_dist, d1, d2, d3, d4)

    return min_dist


# ----------------------------------------------------------
# Main Calculation Router
# ----------------------------------------------------------
def calculate(action, entityType, ColorCode,
              ColorCode2=None, type2=None, db=None):

    entity = db.get_entity(ColorCode, entityType)

    if entity is None:
        return 0

    if action == "area":
        return calc_area(entity)

    if action == "sum_area":
        entities = db.get_entities(ColorCode, entityType)
        if entities is None:
            return 0
        total = 0
        for _, ent in entities.iterrows():
            total += calc_area(ent)
        return total

    if action == "length":
        return calc_length(entity)

    if action == "parallel_distance":
        entity2 = db.get_entity(ColorCode2, type2)
        if entity2 is None:
            return 0
        return calc_parallel_distance(entity, entity2)

    return 0

# side_setback_distance1 = calculate("parallel_distance", "LINE", 6, 10, "LWPOLYLINE", db=CADData(df))
# print(side_setback_distance1)

# ---------------------------------------------
#  Setup
# ---------------------------------------------
db = CADData(df)

def fmt(v, decimals=2):
    """Round numerics, pass through errors."""
    try:
        return round(float(v), decimals)
    except:
        return v

def get_num(v, default=0):
    try:
        return float(v)
    except:
        return default


# ---------------------------------------------
#  Helper: Generalized CAD calculation wrapper
# ---------------------------------------------
def safe_calc(*args, db=None, default=0):
    try:
        return get_num(calculate(*args, db=db))
    except:
        return default


# ---------------------------------------------
#  Floor Codes Mapping
# ---------------------------------------------
floor_codes = {
    "ground": 215,
    "first": 195,
    "second": 196,
    "third": 197,
    "fourth": 198,
    "fifth": 199,
    "sixth": 200
}

floor_areas = {}

# Auto-calculate only floors that exist (non-zero)
for floor_name, code in floor_codes.items():
    raw = safe_calc("area", "LWPOLYLINE", code, db=db)
    if raw > 0:  # floor exists
        floor_areas[floor_name] = fmt(raw)


# ---------------------------------------------
#  Other Direct Values
# ---------------------------------------------
plot_area = fmt(safe_calc("area", "LWPOLYLINE", 7, db=db))

rear_set_back  = fmt(safe_calc("parallel_distance", "LINE", 3, 10, "LWPOLYLINE", db=db))
rear_set_back_len  = fmt(safe_calc("length", "LINE", 3, db=db))

front_set_back = fmt(safe_calc("parallel_distance", "LINE", 4, 10, "LWPOLYLINE", db=db))
front_set_back_len  = fmt(safe_calc("length", "LINE", 4, db=db))

side_setback_distance1 = fmt(safe_calc("parallel_distance", "LINE", 6, 10, "LWPOLYLINE", db=db))
side_setback_distance1_len  = fmt(safe_calc("length", "LINE", 6, db=db))

side_setback_distance2 = fmt(safe_calc("parallel_distance", "LINE", 2, 10, "LWPOLYLINE", db=db))
side_setback_distance2_len  = fmt(safe_calc("length", "LINE", 2, db=db))

road_width       = fmt(safe_calc("length", "LINE", 41, db=db))
building_height  = fmt(safe_calc("length", "LINE", 151, db=db))
max_ground_cov   = fmt(safe_calc("area", "LWPOLYLINE", 10, db=db))
mumty_height     = fmt(safe_calc("length", "LINE", 45, db=db))

# parking values

open_parking_area    = fmt(calculate("sum_area", "LWPOLYLINE", 20, db=db))
car_parking_area    = fmt(calculate("sum_area", "LWPOLYLINE", 140, db=db))
mechanical_parking_area    = fmt(calculate("sum_area", "LWPOLYLINE", 213, db=db))
stilt_parking_area    = fmt(calculate("sum_area", "LWPOLYLINE", 15, db=db))
basement_parking_area    = fmt(calculate("sum_area", "LWPOLYLINE", 31, db=db))


guard_room       = fmt(safe_calc("area", "LWPOLYLINE", 182, db=db))
meter_room       = fmt(safe_calc("area", "LWPOLYLINE", 192, db=db))
mumty_area       = fmt(safe_calc("area", "LWPOLYLINE", 9, db=db))
green_area       = fmt(safe_calc("sum_area", "LWPOLYLINE", 60, db=db))
canopy_area = fmt(safe_calc("area","LWPOLYLINE",184,db=db))
stairs_area  = fmt(safe_calc("sum_area","LWPOLYLINE",115,db=db))
fire_stairs  = fmt(safe_calc("sum_area","LWPOLYLINE",116,db=db))
loading_unloading_area  = fmt(safe_calc("area","LWPOLYLINE",221,db=db))
ground_area = floor_areas.get("ground", 0)

# Total ground floor area including ancillary rooms
total_ground_floor_area = fmt(ground_area + guard_room + meter_room)

total_stair_case_area = fmt(stairs_area + fire_stairs)

# ---------------------------------------------
#  DERIVED METRICS
# ---------------------------------------------
# Total built-up area = sum of all detected floors
total_floor_builtup = fmt(sum(floor_areas.values()))
Far_area = fmt(total_floor_builtup - total_stair_case_area)
# FAR
FAR_value = fmt( Far_area/ plot_area) if plot_area else 0

# Ground coverage %
max_ground_coverage_pre = fmt(max_ground_cov / plot_area * 100) if plot_area else 0
open_area = fmt(plot_area - total_ground_floor_area)
chargable_area = fmt(sum(floor_areas.values()) + mumty_area + guard_room + meter_room)
covered_area = fmt(sum(floor_areas.values()) + mumty_area + guard_room + meter_room)
rain_water_harvesting = fmt(safe_calc("area","LWPOLYLINE",94,db=db))
# ---------------------------------------------

print(plot_area)

import ast

path = "/content/drive/MyDrive/SIDA/New_rules.json"

with open(path, "r") as f:
    text = f.read()

RULES = ast.literal_eval(text)

print("Rules loaded:", len(RULES))

# Parking area rules
plot_usage = 0.3 if plot_area<1000 else 0.5
ecs = (Far_area * plot_usage)/100

permissible_open_parking = ecs * 23
permissible_stilt_parking = ecs * 28
permissible_basement_parking = ecs * 32
permissible_mechanical_parking = ecs * 64

# ------------------------------------------
#  VALIDATOR
# ------------------------------------------

# RULES = [... your existing RULES list ...]

# ------------------------------------------
# LOCATION MATCHING
# ------------------------------------------
def location_matches(rule_location, input_location):
    if rule_location == input_location:
        return True
    if rule_location == "Urban/Rural":
        return input_location in ["Urban", "Rural"]
    return False

def area_type_matches(rule_area_type, input_area_type):
    # Split rule entry by "/" → e.g. "Cottage/Micro/Household"
    allowed_types = [t.strip().lower() for t in rule_area_type.split("/")]

    # Normalize input
    input_type = input_area_type.strip().lower()

    # Return True if input matches any allowed type
    return input_type in allowed_types

# ------------------------------------------
# SELECT RULE BASED ON INPUT CONDITIONS
# ------------------------------------------
def get_applicable_rule(area_type, location, plot_area, road_width):
    for rule in RULES:
        if not area_type_matches(rule["area_type"], area_type):
            continue
        if not location_matches(rule["location"], location):
            continue

        if not (rule["plot_min"] <= plot_area <= (rule["plot_max"] if rule["plot_max"] else plot_area)):
            continue

        if road_width < rule["road_min"]:
            continue

        if rule.get("road_max") is not None and road_width >= rule["road_max"]:
            continue

        return rule

    return None


# ------------------------------------------
# SELECT REQUIRED SETBACKS BASED ON HEIGHT
# ------------------------------------------
def get_required_setbacks(rule, height):
    height_bands = rule.get("height_bands", [])
    for band in height_bands:
        if height <= band["h_max"]:
            return {
                "front": band["F"],
                "back": band["B"],
                "side1": band["S1"],
                "side2": band["S2"]
            }
    return None


# ------------------------------------------
# MAIN VALIDATION FUNCTION (NO EARLY FAIL)
# ------------------------------------------
def validate(area_type, location, plot_area, road_width,
             proposed_FAR, coverage_area, height,
             parking_area,
             open_parking_area,
              basement_parking_area,
              stilt_parking_area,
              mechanical_parking_area,
             provided_setbacks=None,

             ):

    if provided_setbacks is None:
        provided_setbacks = {}

    rule = get_applicable_rule(area_type, location, plot_area, road_width)

    print(rule)

    if rule is None:
        return {"status": "FAIL",
                "failures":
                 [f"No matching rule for plot size {plot_area}, location {location}, building type {area_type}"],
                "details": []
                }

    pass_list = []
    fail_list = []

    # -----------------------------------
    # FAR CHECK
    # -----------------------------------
    if proposed_FAR > rule["FAR"]:
        fail_list.append(f"FAR : Allowed ≤ {rule['FAR']}, In Map = {proposed_FAR}")
    else:
        pass_list.append(f"FAR : In Map = {proposed_FAR}, Allowed ≤ {rule['FAR']}")

    # -----------------------------------
    # COVERAGE CHECK
    # -----------------------------------
    if rule["coverage_percent"] is not None:
        allowed_coverage =rule["coverage_percent"]
        if coverage_area > allowed_coverage:
            fail_list.append(
                f" Ground Coverage Percent : Allowed ≤ {allowed_coverage:.2f} %, In Map = {coverage_area}%"
            )
        else:
            pass_list.append(
                f"Ground Coverage Percent : In Map = {coverage_area} %, Allowed ≤ {allowed_coverage:.2f} %"
            )
    # Rain water harvesting
    ground_floor_area = floor_areas.get("ground", 0)

    min_req_har = 0
    if ground_floor_area > 400:
        min_req_har = ((ground_floor_area - 400)*0.5/50) + 3.5
    else:
        min_req_har = 3.5
    depth = 6
    if rain_water_harvesting*depth < min_req_har:
        fail_list.append(
                f"Rain Water Harvesting : Allowed ≥ {min_req_har:.2f} Cu.M, In Map = {rain_water_harvesting*depth:.2f}Cu.M"
            )

    else:
        pass_list.append(
                f"Rain Water Harvesting Percent : In Map = {rain_water_harvesting*depth:.2f} Cu.M, Allowed ≥ {min_req_har:.2f} Cu.M"
            )



    # Loading/Unloading
    if Far_area/1000 <= 1:
        if loading_unloading_area <26.25:
          fail_list.append(
                f"Loading/Unloading: Allowed ≥ {26.25} Sq.M, In Map = {loading_unloading_area:.2f} Sq.M"
            )
        else:
          pass_list.append(
                f"Loading/Unloading: In Map = {loading_unloading_area} Sq.M, Allowed ≥ {26.25} Sq.M"
            )
    else:
        if loading_unloading_area <(26.25*(Far_area/1000)):
          fail_list.append(
                f"Loading/Unloading: Allowed ≥ {26.25*(Far_area/1000):.2f} Sq.M, In Map = {loading_unloading_area:.2f} Sq.M"
            )
        else:
          pass_list.append(
                f"Loading/Unloading: In Map = {loading_unloading_area} Sq.M, Allowed ≥ {26.25*(Far_area/1000)} Sq.M"
            )




    # -----------------------------------
    # HEIGHT CHECK
    # -----------------------------------
    max_h = rule["max_building_height"]
    if height > max_h:
        fail_list.append(
            f"Building Height : Allowed ≤ {max_h} m, In Map = {height} m"
        )
    else:
        pass_list.append(
            f"Building Height : In Map = {height} m, Allowed ≤ {max_h} m"
        )

    #  Parking rule

    # open_parking_area
    # car_parking_area
    # mechanical_parking_area
    # stilt_parking_area
    # basement_parking_area


    # OPEN PARKING
    if open_parking_area>0:
      if open_parking_area < parking_area["permissible_open_parking"]:
          fail_list.append(
              f"Open Parking area : Allowed ≥ {parking_area['permissible_open_parking']:.2f} Sq.M, In Map = {open_parking_area:.2f} Sq.M"
          )
      else:
          pass_list.append(
              f"Open Parking area : In Map = {open_parking_area:.2f} Sq.M, Allowed ≥ {parking_area['permissible_open_parking']:.2f} Sq.M"
          )


    # BASEMENT PARKING
    if basement_parking_area>0:
      if  basement_parking_area < parking_area["permissible_basement_parking"]:
          fail_list.append(
              f"Basement Parking area : Allowed ≥ {parking_area['permissible_basement_parking']:.2f} Sq.M, In Map = {basement_parking_area:.2f} Sq.M"
          )
      else:
          pass_list.append(
              f"Basement Parking area : In Map = {basement_parking_area:.2f} Sq.M, Allowed ≥ {parking_area['permissible_basement_parking']:.2f} Sq.M"
          )

    if stilt_parking_area > 0:
      if  stilt_parking_area < parking_area["permissible_stilt_parking"]:
          fail_list.append(
              f"Stilt Parking area : Allowed ≥ {parking_area['permissible_stilt_parking']:.2f} Sq.M, In Map = {stilt_parking_area:.2f} Sq.M"
          )
      else:
          pass_list.append(
              f"Stilt Parking area : In Map = {stilt_parking_area:.2f} Sq.M, Allowed ≥ {parking_area['permissible_stilt_parking']:.2f} Sq.M"
          )

    # MECHANICAL PARKING

    if mechanical_parking_area > 0:
      if mechanical_parking_area < parking_area["permissible_mechanical_parking"]:
          fail_list.append(
              f"Mechanical Parking area : Allowed ≥ {parking_area['permissible_mechanical_parking']:.2f} Sq.M, In Map = {mechanical_parking_area:.2f} Sq.M"
          )
      else:
          pass_list.append(
              f"Mechanical Parking area : In Map = {mechanical_parking_area:.2f} Sq.M, Allowed ≥ {parking_area['permissible_mechanical_parking']:.2f} Sq.M"
          )



    # -----------------------------------
    # OPTIONAL SETBACK CHECK
    # -----------------------------------
    if provided_setbacks:
        required = get_required_setbacks(rule, height)
        # print("\n",required)
        for key, label in {
            "front": "Front",
            "back": "Rear",
            "side1": "Side 1",
            "side2": "Side 2"
        }.items():

            if key in provided_setbacks:
                current = provided_setbacks[key]
                req = required[key]

                if current < req:
                    fail_list.append(
                        f"{label} setback : Allowed ≥ {req} m, In Map = {current} m"
                    )
                else:
                    pass_list.append(
                        f"{label} setback : In Map = {current} m, Allowed ≥ {req} m"
                    )

        # Open area

        # min 25% of all set back

        old_all_set_back_area = ((front_set_back_len*required['front'])+(rear_set_back_len*required['back'])+(side_setback_distance1_len-(front_set_back+rear_set_back)*required['side1'])
        +(side_setback_distance2_len-(front_set_back+rear_set_back)*required['side2']))*0.25

        all_set_back_area = (
                (front_set_back_len * required['front']) +
                (rear_set_back_len * required['back']) +
                ((side_setback_distance1_len - (required['front'] + required['back'])) * required['side1']) +
                ((side_setback_distance2_len - (required['front'] + required['back'])) * required['side2'])
            ) * 0.25



        if green_area > all_set_back_area:
            pass_list.append(f"Green area: In Map = {green_area} Sq.M, Allowed ≥ {all_set_back_area:.2f} Sq.M")
        else:
            fail_list.append(f"Green area: Allowed ≥ {all_set_back_area:.2f} Sq.M, In Map = {green_area} Sq.M")

    # -----------------------------------
    # FINAL RESULT
    # -----------------------------------
    status = "PASS" if len(fail_list) == 0 else "FAIL"
    return {"status": status, "failures": fail_list, "details": pass_list}


# ------------------------------------------
# EXAMPLE USAGE
# ------------------------------------------
result = validate(
    area_type="Industrial Unit",  # (Industrial Unit,Cottage/Micro/Household,Industrial Flatted Units,IT Unit
    location="Urban", #  (Rural)
    plot_area=plot_area,
    road_width=road_width,
    proposed_FAR=FAR_value,
    coverage_area=max_ground_coverage_pre,
    height=building_height,
    provided_setbacks={
        "front": front_set_back,
        "back": rear_set_back,
        "side1": side_setback_distance1,
        "side2": side_setback_distance2
    },
    open_parking_area=open_parking_area,
    basement_parking_area=basement_parking_area,
    stilt_parking_area=stilt_parking_area,
    mechanical_parking_area=mechanical_parking_area,
    parking_area={
        "permissible_open_parking" : permissible_open_parking,
        "permissible_stilt_parking" :permissible_stilt_parking,
        "permissible_basement_parking" :permissible_basement_parking,
        "permissible_mechanical_parking" :permissible_mechanical_parking
    }

)

print(stilt_parking_area)
print(permissible_stilt_parking)

# ------------------------------------------
# PRINTABLE REPORT
# ------------------------------------------
def fmt(v):
    return "-" if v is None else v

FileName = os.path.splitext(os.path.basename(dxf_filename))[0]

report = "\n" + "="*80 + "\n"
report += f"     INDUSTRIAL BUILDING VALIDATION REPORT of AutoCad {FileName}\n"
report += "="*80 + "\n\n"

report += "-"*80 + "\n"
report += "Fetched Details\n" + "-"*80 + "\n\n"

report += f"{'S.No':<6} {'Types':<45} {'Values'}\n"
report += "-"*80 + "\n"

# Serial number counter
sno = 1

# Plot area
report += f"{sno:<6} {'Plot Area':<45}: {fmt(plot_area)} Sq.M.\n"
sno += 1

# ----------------------------------------------------
# Dynamic Floor Printing
# ----------------------------------------------------
floor_print_names = {
    "ground": "Existing Ground Floor Area",
    "first": "Existing First Floor Area",
    "second": "Existing Second Floor Area",
    "third": "Existing Third Floor Area",
    "fourth": "Existing Fourth Floor Area",
    "fifth": "Existing Fifth Floor Area",
    "sixth": "Existing Sixth Floor Area"
}

for key, label in floor_print_names.items():
    if key in floor_areas:
        report += f"{sno:<6} {label:<45}: {fmt(floor_areas[key])} Sq.M.\n"
        sno += 1

# Total Ground Floor
report += f"{sno:<6} {'Total Ground Coverage Inclusive Non FAR area':<45}: {fmt(total_ground_floor_area)} Sq.M.\n"
sno += 1

# ----------------------------------------------------
# Setbacks
# ----------------------------------------------------
report += f"{sno:<6} {'Front Setback':<45}: {fmt(front_set_back)} M\n"
sno += 1
report += f"{sno:<6} {'Rear Setback':<45}: {fmt(rear_set_back)} M\n"
sno += 1
report += f"{sno:<6} {'Side Setback (1)':<45}: {fmt(side_setback_distance1)} M\n"
sno += 1
report += f"{sno:<6} {'Side Setback (2)':<45}: {fmt(side_setback_distance2)} M\n"
sno += 1

# ----------------------------------------------------
# Road, FAR, Height
# ----------------------------------------------------
report += f"{sno:<6} {'Road Width':<45}: {fmt(road_width)} M\n"
sno += 1
report += f"{sno:<6} {'FAR area':<45}: {fmt(Far_area)} Sq.M.\n"
sno += 1
report += f"{sno:<6} {'FAR':<45}: {fmt(FAR_value)}\n"
sno += 1
report += f"{sno:<6} {'Building Height':<45}: {fmt(building_height)} M\n"
sno += 1
report += f"{sno:<6} {'Loading and Unloading area':<45}: {fmt(loading_unloading_area)} M\n"
sno += 1
# Parking
if open_parking_area > 0:
    report += f"{sno:<6} {'Open Area Parking':<45}: {fmt(open_parking_area)} M\n"
    sno += 1
if stilt_parking_area>0:
    report += f"{sno:<6} {'Stilt Area Parking':<45}: {fmt(stilt_parking_area)} Sq.M\n"
    sno += 1
if basement_parking_area > 0:
    report += f"{sno:<6} {'Basement Area Parking':<45}: {fmt(basement_parking_area)} M\n"
    sno += 1

if mechanical_parking_area > 0:
    report += f"{sno:<6} {'Mechanical Area Parking':<45}: {fmt(mechanical_parking_area)} M\n"
    sno += 1

# report += f"{sno:<6} {'Open Area Parking':<45}: {fmt(open_parking_area)} M\n"
# sno += 1
# ----------------------------------------------------
# Guard + Meter Room + Mumty + Coverage
# ----------------------------------------------------
report += f"{sno:<6} {'Existing Guard/Meter Room Area':<45}: {fmt(guard_room + meter_room)} Sq.M.\n"
sno += 1
report += f"{sno:<6} {'Existing Mumty Area':<45}: {fmt(mumty_area)} Sq.M.\n"
sno += 1
report += f"{sno:<6} {'Covered Area':<45}: {fmt(covered_area)} Sq.M.\n"
sno += 1
report += f"{sno:<6} {'Ground Coverage':<45}: {fmt(max_ground_cov)} Sq.M. ({max_ground_coverage_pre}%)\n"
sno += 1
report += f"{sno:<6} {'Open Area':<45}: {fmt(open_area)} Sq.M.\n"
sno += 1
report += f"{sno:<6} {'Total Stair Case Area':<45}: {fmt(total_stair_case_area)} Sq.M.\n"
sno += 1
report += f"{sno:<6} {'Total Chargeable Area':<45}: {fmt(chargable_area)} Sq.M.\n"
sno += 1

# ----------------------------------------------------
# Scrutiny Report
# ----------------------------------------------------
report += "\n" + "-"*80 + "\n"
report += "Scrutiny Report\n"
report += "-"*80 + "\n\n"

if result["failures"]:
    report += "FAILED CHECKS:\n"
    for i, f in enumerate(result["failures"], 1):
        report += f"   {i}. ✖ {f}\n"
    report += "\n"

if result["details"]:
    report += "PASSED CHECKS:\n"
    for i, p in enumerate(result["details"], 1):
        report += f"   {i}. ✔ {p}\n"

report += "\n" + "="*80 + "\n"

print(report)

# ===============================
# CREATE PDF WITH COLORED PASS/FAIL TEXT
# ===============================

from reportlab.pdfgen import canvas
from reportlab.lib.colors import red, green, black
# The following imports and font registration are causing the error
# and are not needed for the built-in Courier font.
# from reportlab.pdfbase.ttfonts import TTFont
# from reportlab.pdfbase import pdfmetrics

# Register monospaced font for exact formatting - REMOVED
# pdfmetrics.registerFont(TTFont('Courier', 'Courier.ttf'))

pdf_file = f"{FileName}.pdf"
c = canvas.Canvas(pdf_file)

# Starting position
x = 40
y = 800
line_height = 12  # space between lines

# Split text into lines
lines = report.split("\n")

for line in lines:

    # Automatic page break
    if y < 40:  # bottom margin
        c.showPage()
        c.setFont("Courier", 10)  # Using built-in Courier font
        y = 800

    # Decide color rules
    if ("✖" in line or "FAIL" in line or
        "FAILED" in line):
        c.setFillColor(red)

    elif ("✔" in line or "PASS" in line or
          "PASSED" in line):
        c.setFillColor(green)

    else:
        c.setFillColor(black)

    # Draw the text
    c.setFont("Courier", 10)  # Using built-in Courier font
    c.drawString(x, y, line)
    y -= line_height

# Save PDF
c.save()

# Download PDF in Colab
from google.colab import files
files.download(pdf_file)

print("PDF created:", pdf_file)



summary = """
This Colab notebook performs an automated architectural and engineering validation process for CAD (DXF) drawings. Here's a summary of its key functionalities:

*   **Dependency Installation**: It sets up the environment by installing `ezdxf` for DXF parsing and `reportlab` for PDF generation.
*   **DXF to CSV Conversion**: It includes functions to read DXF files, extract geometric and textual entity data (lines, circles, polylines, text, etc.), and convert this information into a CSV format in memory.
*   **Data Loading and Initial Processing**: The notebook mounts Google Drive to access DXF files, processes a selected DXF file into a CSV string, and then loads this data into a Pandas DataFrame for structured analysis. The generated CSV data can also be downloaded.
*   **CAD Data Analysis Functions**: A suite of helper functions and a `CADData` class are defined to perform various geometric calculations (e.g., area, length, parallel distance) on specific entities identified by their type and color codes within the DataFrame.
*   **Metric Calculation**: It calculates numerous architectural and engineering metrics directly from the processed CAD data, such as plot area, individual floor areas, setbacks (front, rear, side), road width, building height, Floor Area Ratio (FAR), ground coverage percentage, and different types of parking areas (open, stilt, basement, mechanical).
*   **Rule Loading**: An external JSON file containing a set of validation rules (`New_rules.json`) is loaded into the notebook. These rules define permissible values and conditions for various building parameters based on plot characteristics.
*   **Validation Logic**: An extensive `validate` function is implemented to compare the calculated CAD metrics against the loaded rules. This function checks for compliance in areas like FAR, ground coverage, building height, required setbacks, rain water harvesting requirements, loading/unloading areas, and parking provisions.
*   **Report Generation**: It dynamically generates a comprehensive text-based validation report that summarizes the extracted CAD details and clearly lists which checks passed (✔) and which failed (✖) according to the rules.
*   **PDF Export**: Finally, the generated text report is converted into a professional, color-coded PDF document (with red indicating failures and green for passes) and provided for download, offering an easily shareable and readable summary of the validation results.
"""

print(summary)

